version: '3'

services:
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data:
